activeDb: mariadb
source:
    host: localhost
    port: 3306
    user: root
    password: root
    database: metabase
target:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: metabase_target